//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buzzer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Buzzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buzzer: Ошибка.
        /// </summary>
        internal static string BuzzerErrorMessageBoxCaption {
            get {
                return ResourceManager.GetString("BuzzerErrorMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список кредитов.
        /// </summary>
        internal static string CreditsListViewModel_Caption {
            get {
                return ResourceManager.GetString("CreditsListViewModel_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При сохранении информации в базу данных возникла ошибка. См. логи..
        /// </summary>
        internal static string ErrorWhileSavingInformationToDatabase {
            get {
                return ResourceManager.GetString("ErrorWhileSavingInformationToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buzzer.
        /// </summary>
        internal static string MainWindowViewModel_BuzzerCaption {
            get {
                return ResourceManager.GetString("MainWindowViewModel_BuzzerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список кредитов.
        /// </summary>
        internal static string MainWindowViewModel_CreditsList {
            get {
                return ResourceManager.GetString("MainWindowViewModel_CreditsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поручительство.
        /// </summary>
        internal static string MainWindowViewModel_GuaranteeCredit {
            get {
                return ResourceManager.GetString("MainWindowViewModel_GuaranteeCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий мониторинг.
        /// </summary>
        internal static string MainWindowViewModel_NotificationLog {
            get {
                return ResourceManager.GetString("MainWindowViewModel_NotificationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оповещение платежей.
        /// </summary>
        internal static string MainWindowViewModel_PaymentNotificationList {
            get {
                return ResourceManager.GetString("MainWindowViewModel_PaymentNotificationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый кредит.
        /// </summary>
        internal static string NewCreditTabCaption {
            get {
                return ResourceManager.GetString("NewCreditTabCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий мониторинг.
        /// </summary>
        internal static string NotificationLogViewModel_Caption {
            get {
                return ResourceManager.GetString("NotificationLogViewModel_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оповещение платежей.
        /// </summary>
        internal static string PaymentNotificationListViewModel_Caption {
            get {
                return ResourceManager.GetString("PaymentNotificationListViewModel_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникла ошибка при попытке отправить СМС. См. логи..
        /// </summary>
        internal static string SendSmsError {
            get {
                return ResourceManager.GetString("SendSmsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указан неизвестный мобильный провайдер..
        /// </summary>
        internal static string UnknownMobileProvider {
            get {
                return ResourceManager.GetString("UnknownMobileProvider", resourceCulture);
            }
        }
    }
}
