//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buzzer.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Buzzer.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM NotificationLog;
        ///DELETE FROM PhoneNumbers;
        ///DELETE FROM Persons;
        ///DELETE FROM PaymentsSchedule;
        ///DELETE FROM Credits;.
        /// </summary>
        internal static string ClearDatabase {
            get {
                return ResourceManager.GetString("ClearDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TEMP TABLE ID (Value integer);
        ///
        ///INSERT INTO Credits
        ///	(CreditNumber, CreditAmount, CreditIssueDate, MonthsCount, DiscountRate, EffectiveDiscountRate, ExchangeRate)
        ///VALUES
        ///	(&apos;CNE1&apos;, 100000, &apos;2013-12-31&apos;, 12, 0.36, 0.24, 45);
        ///
        ///INSERT INTO ID VALUES ((SELECT last_insert_rowid()));
        ///
        ///INSERT INTO Persons
        ///	(CreditID, PersonalNumber, Name, RegistrationAddress, FactAddress, PassportNumber, PassportIssueDate, PassportIssuer, IsBorrower)
        ///VALUES
        ///	((SELECT Value FROM ID LIMIT 1), &apos;11111111111111&apos;, &apos;Bor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenerateTestDataForEditTest {
            get {
                return ResourceManager.GetString("GenerateTestDataForEditTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TEMP TABLE ID (CreditID integer, PersonID integer);
        ///
        ///INSERT INTO Credits
        ///	(CreditNumber, CreditAmount, CreditIssueDate, MonthsCount, DiscountRate, EffectiveDiscountRate, ExchangeRate)
        ///VALUES
        ///	(&apos;CNSNLI1&apos;, 100000, &apos;2013-12-31&apos;, 12, 0.36, 0.24, 45);
        ///
        ///INSERT INTO ID (CreditID, PersonID) VALUES ((SELECT last_insert_rowid()), 0);
        ///
        ///INSERT INTO Persons
        ///	(CreditID, PersonalNumber, Name, RegistrationAddress, FactAddress, PassportNumber, PassportIssueDate, PassportIssuer, IsBorrower)
        ///VALUES
        ///	((SELEC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenerateTestDataForSaveNotificationLogItemsTest {
            get {
                return ResourceManager.GetString("GenerateTestDataForSaveNotificationLogItemsTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TEMP TABLE ID (CreditID integer, PersonID integer);
        ///
        ///INSERT INTO Credits
        ///	(CreditNumber, CreditAmount, CreditIssueDate, MonthsCount, DiscountRate, EffectiveDiscountRate, ExchangeRate)
        ///VALUES
        ///	(&apos;CNSNLI1&apos;, 100000, &apos;2013-12-31&apos;, 12, 0.36, 0.24, 45);
        ///
        ///INSERT INTO ID (CreditID, PersonID) VALUES ((SELECT last_insert_rowid()), 0);
        ///
        ///INSERT INTO Persons
        ///	(CreditID, PersonalNumber, Name, RegistrationAddress, FactAddress, PassportNumber, PassportIssueDate, PassportIssuer, IsBorrower)
        ///VALUES
        ///	((SELEC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenerateTestDataForSelectNotificationLogItemsTest {
            get {
                return ResourceManager.GetString("GenerateTestDataForSelectNotificationLogItemsTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TEMP TABLE ID (Value integer);
        ///
        ///-- Credit without Guarantors.
        ///INSERT INTO Credits
        ///	(CreditNumber, CreditAmount, CreditIssueDate, MonthsCount, DiscountRate, EffectiveDiscountRate, ExchangeRate)
        ///VALUES
        ///	(&apos;CNS1&apos;, 200000, &apos;2014-01-02&apos;, 24, 0.36, 0.12, 47.5);
        ///	
        ///INSERT INTO ID VALUES ((SELECT last_insert_rowid()));
        ///
        ///INSERT INTO Persons
        ///	(CreditID, PersonalNumber, Name, RegistrationAddress, FactAddress, PassportNumber, PassportIssueDate, PassportIssuer, IsBorrower)
        ///VALUES
        ///	((SELECT Value FROM I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenerateTestDataForSelectTest {
            get {
                return ResourceManager.GetString("GenerateTestDataForSelectTest", resourceCulture);
            }
        }
    }
}
