//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BuzzerDatabaseModel", "FK__PersonsTo__Credi__173876EA", "Credits", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Buzzer.DataAccess.Credit), "PersonsToCredits", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Buzzer.DataAccess.PersonsToCredit), true)]
[assembly: EdmRelationshipAttribute("BuzzerDatabaseModel", "FK__PersonsTo__Perso__182C9B23", "Persons", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Buzzer.DataAccess.Person), "PersonsToCredits", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Buzzer.DataAccess.PersonsToCredit), true)]
[assembly: EdmRelationshipAttribute("BuzzerDatabaseModel", "FK__PhoneNumb__Perso__0BC6C43E", "Persons", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Buzzer.DataAccess.Person), "PhoneNumbers", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Buzzer.DataAccess.PhoneNumber), true)]

#endregion

namespace Buzzer.DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BuzzerDatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BuzzerDatabaseEntities object using the connection string found in the 'BuzzerDatabaseEntities' section of the application configuration file.
        /// </summary>
        public BuzzerDatabaseEntities() : base("name=BuzzerDatabaseEntities", "BuzzerDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BuzzerDatabaseEntities object.
        /// </summary>
        public BuzzerDatabaseEntities(string connectionString) : base(connectionString, "BuzzerDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BuzzerDatabaseEntities object.
        /// </summary>
        public BuzzerDatabaseEntities(EntityConnection connection) : base(connection, "BuzzerDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Credit> Credits
        {
            get
            {
                if ((_Credits == null))
                {
                    _Credits = base.CreateObjectSet<Credit>("Credits");
                }
                return _Credits;
            }
        }
        private ObjectSet<Credit> _Credits;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Person> Persons
        {
            get
            {
                if ((_Persons == null))
                {
                    _Persons = base.CreateObjectSet<Person>("Persons");
                }
                return _Persons;
            }
        }
        private ObjectSet<Person> _Persons;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PersonsToCredit> PersonsToCredits
        {
            get
            {
                if ((_PersonsToCredits == null))
                {
                    _PersonsToCredits = base.CreateObjectSet<PersonsToCredit>("PersonsToCredits");
                }
                return _PersonsToCredits;
            }
        }
        private ObjectSet<PersonsToCredit> _PersonsToCredits;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PhoneNumber> PhoneNumbers
        {
            get
            {
                if ((_PhoneNumbers == null))
                {
                    _PhoneNumbers = base.CreateObjectSet<PhoneNumber>("PhoneNumbers");
                }
                return _PhoneNumbers;
            }
        }
        private ObjectSet<PhoneNumber> _PhoneNumbers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Credits EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCredits(Credit credit)
        {
            base.AddObject("Credits", credit);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Persons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPersons(Person person)
        {
            base.AddObject("Persons", person);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PersonsToCredits EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPersonsToCredits(PersonsToCredit personsToCredit)
        {
            base.AddObject("PersonsToCredits", personsToCredit);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PhoneNumbers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhoneNumbers(PhoneNumber phoneNumber)
        {
            base.AddObject("PhoneNumbers", phoneNumber);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BuzzerDatabaseModel", Name="Credit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Credit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Credit object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="creditNumber">Initial value of the CreditNumber property.</param>
        public static Credit CreateCredit(global::System.Int32 id, global::System.String creditNumber)
        {
            Credit credit = new Credit();
            credit.ID = id;
            credit.CreditNumber = creditNumber;
            return credit;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreditNumber
        {
            get
            {
                return _CreditNumber;
            }
            set
            {
                OnCreditNumberChanging(value);
                ReportPropertyChanging("CreditNumber");
                _CreditNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreditNumber");
                OnCreditNumberChanged();
            }
        }
        private global::System.String _CreditNumber;
        partial void OnCreditNumberChanging(global::System.String value);
        partial void OnCreditNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CreditAmount
        {
            get
            {
                return _CreditAmount;
            }
            set
            {
                OnCreditAmountChanging(value);
                ReportPropertyChanging("CreditAmount");
                _CreditAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreditAmount");
                OnCreditAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _CreditAmount;
        partial void OnCreditAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnCreditAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreditIssueDate
        {
            get
            {
                return _CreditIssueDate;
            }
            set
            {
                OnCreditIssueDateChanging(value);
                ReportPropertyChanging("CreditIssueDate");
                _CreditIssueDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreditIssueDate");
                OnCreditIssueDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreditIssueDate;
        partial void OnCreditIssueDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreditIssueDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MonthsCount
        {
            get
            {
                return _MonthsCount;
            }
            set
            {
                OnMonthsCountChanging(value);
                ReportPropertyChanging("MonthsCount");
                _MonthsCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MonthsCount");
                OnMonthsCountChanged();
            }
        }
        private Nullable<global::System.Int32> _MonthsCount;
        partial void OnMonthsCountChanging(Nullable<global::System.Int32> value);
        partial void OnMonthsCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DiscountRate
        {
            get
            {
                return _DiscountRate;
            }
            set
            {
                OnDiscountRateChanging(value);
                ReportPropertyChanging("DiscountRate");
                _DiscountRate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiscountRate");
                OnDiscountRateChanged();
            }
        }
        private Nullable<global::System.Decimal> _DiscountRate;
        partial void OnDiscountRateChanging(Nullable<global::System.Decimal> value);
        partial void OnDiscountRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> EffectiveDiscountRate
        {
            get
            {
                return _EffectiveDiscountRate;
            }
            set
            {
                OnEffectiveDiscountRateChanging(value);
                ReportPropertyChanging("EffectiveDiscountRate");
                _EffectiveDiscountRate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EffectiveDiscountRate");
                OnEffectiveDiscountRateChanged();
            }
        }
        private Nullable<global::System.Decimal> _EffectiveDiscountRate;
        partial void OnEffectiveDiscountRateChanging(Nullable<global::System.Decimal> value);
        partial void OnEffectiveDiscountRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ExchangeRate
        {
            get
            {
                return _ExchangeRate;
            }
            set
            {
                OnExchangeRateChanging(value);
                ReportPropertyChanging("ExchangeRate");
                _ExchangeRate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExchangeRate");
                OnExchangeRateChanged();
            }
        }
        private Nullable<global::System.Decimal> _ExchangeRate;
        partial void OnExchangeRateChanging(Nullable<global::System.Decimal> value);
        partial void OnExchangeRateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BuzzerDatabaseModel", "FK__PersonsTo__Credi__173876EA", "PersonsToCredits")]
        public EntityCollection<PersonsToCredit> PersonsToCredits
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PersonsToCredit>("BuzzerDatabaseModel.FK__PersonsTo__Credi__173876EA", "PersonsToCredits");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PersonsToCredit>("BuzzerDatabaseModel.FK__PersonsTo__Credi__173876EA", "PersonsToCredits", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BuzzerDatabaseModel", Name="Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Person CreatePerson(global::System.Int32 id, global::System.String name)
        {
            Person person = new Person();
            person.ID = id;
            person.Name = name;
            return person;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegistrationAddress
        {
            get
            {
                return _RegistrationAddress;
            }
            set
            {
                OnRegistrationAddressChanging(value);
                ReportPropertyChanging("RegistrationAddress");
                _RegistrationAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RegistrationAddress");
                OnRegistrationAddressChanged();
            }
        }
        private global::System.String _RegistrationAddress;
        partial void OnRegistrationAddressChanging(global::System.String value);
        partial void OnRegistrationAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FactAddress
        {
            get
            {
                return _FactAddress;
            }
            set
            {
                OnFactAddressChanging(value);
                ReportPropertyChanging("FactAddress");
                _FactAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FactAddress");
                OnFactAddressChanged();
            }
        }
        private global::System.String _FactAddress;
        partial void OnFactAddressChanging(global::System.String value);
        partial void OnFactAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PassportNumber
        {
            get
            {
                return _PassportNumber;
            }
            set
            {
                OnPassportNumberChanging(value);
                ReportPropertyChanging("PassportNumber");
                _PassportNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PassportNumber");
                OnPassportNumberChanged();
            }
        }
        private global::System.String _PassportNumber;
        partial void OnPassportNumberChanging(global::System.String value);
        partial void OnPassportNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PassportIssueDate
        {
            get
            {
                return _PassportIssueDate;
            }
            set
            {
                OnPassportIssueDateChanging(value);
                ReportPropertyChanging("PassportIssueDate");
                _PassportIssueDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PassportIssueDate");
                OnPassportIssueDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PassportIssueDate;
        partial void OnPassportIssueDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPassportIssueDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PassportIssuer
        {
            get
            {
                return _PassportIssuer;
            }
            set
            {
                OnPassportIssuerChanging(value);
                ReportPropertyChanging("PassportIssuer");
                _PassportIssuer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PassportIssuer");
                OnPassportIssuerChanged();
            }
        }
        private global::System.String _PassportIssuer;
        partial void OnPassportIssuerChanging(global::System.String value);
        partial void OnPassportIssuerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsValid
        {
            get
            {
                return _IsValid;
            }
            set
            {
                OnIsValidChanging(value);
                ReportPropertyChanging("IsValid");
                _IsValid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsValid");
                OnIsValidChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsValid;
        partial void OnIsValidChanging(Nullable<global::System.Boolean> value);
        partial void OnIsValidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BuzzerDatabaseModel", "FK__PersonsTo__Perso__182C9B23", "PersonsToCredits")]
        public EntityCollection<PersonsToCredit> PersonsToCredits
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PersonsToCredit>("BuzzerDatabaseModel.FK__PersonsTo__Perso__182C9B23", "PersonsToCredits");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PersonsToCredit>("BuzzerDatabaseModel.FK__PersonsTo__Perso__182C9B23", "PersonsToCredits", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BuzzerDatabaseModel", "FK__PhoneNumb__Perso__0BC6C43E", "PhoneNumbers")]
        public EntityCollection<PhoneNumber> PhoneNumbers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PhoneNumber>("BuzzerDatabaseModel.FK__PhoneNumb__Perso__0BC6C43E", "PhoneNumbers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PhoneNumber>("BuzzerDatabaseModel.FK__PhoneNumb__Perso__0BC6C43E", "PhoneNumbers", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BuzzerDatabaseModel", Name="PersonsToCredit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PersonsToCredit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PersonsToCredit object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="creditID">Initial value of the CreditID property.</param>
        /// <param name="personID">Initial value of the PersonID property.</param>
        /// <param name="isBorrower">Initial value of the IsBorrower property.</param>
        public static PersonsToCredit CreatePersonsToCredit(global::System.Int32 id, global::System.Int32 creditID, global::System.Int32 personID, global::System.Boolean isBorrower)
        {
            PersonsToCredit personsToCredit = new PersonsToCredit();
            personsToCredit.ID = id;
            personsToCredit.CreditID = creditID;
            personsToCredit.PersonID = personID;
            personsToCredit.IsBorrower = isBorrower;
            return personsToCredit;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CreditID
        {
            get
            {
                return _CreditID;
            }
            set
            {
                OnCreditIDChanging(value);
                ReportPropertyChanging("CreditID");
                _CreditID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreditID");
                OnCreditIDChanged();
            }
        }
        private global::System.Int32 _CreditID;
        partial void OnCreditIDChanging(global::System.Int32 value);
        partial void OnCreditIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PersonID
        {
            get
            {
                return _PersonID;
            }
            set
            {
                OnPersonIDChanging(value);
                ReportPropertyChanging("PersonID");
                _PersonID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PersonID");
                OnPersonIDChanged();
            }
        }
        private global::System.Int32 _PersonID;
        partial void OnPersonIDChanging(global::System.Int32 value);
        partial void OnPersonIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsBorrower
        {
            get
            {
                return _IsBorrower;
            }
            set
            {
                OnIsBorrowerChanging(value);
                ReportPropertyChanging("IsBorrower");
                _IsBorrower = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsBorrower");
                OnIsBorrowerChanged();
            }
        }
        private global::System.Boolean _IsBorrower;
        partial void OnIsBorrowerChanging(global::System.Boolean value);
        partial void OnIsBorrowerChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BuzzerDatabaseModel", "FK__PersonsTo__Credi__173876EA", "Credits")]
        public Credit Credit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Credit>("BuzzerDatabaseModel.FK__PersonsTo__Credi__173876EA", "Credits").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Credit>("BuzzerDatabaseModel.FK__PersonsTo__Credi__173876EA", "Credits").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Credit> CreditReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Credit>("BuzzerDatabaseModel.FK__PersonsTo__Credi__173876EA", "Credits");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Credit>("BuzzerDatabaseModel.FK__PersonsTo__Credi__173876EA", "Credits", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BuzzerDatabaseModel", "FK__PersonsTo__Perso__182C9B23", "Persons")]
        public Person Person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("BuzzerDatabaseModel.FK__PersonsTo__Perso__182C9B23", "Persons").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("BuzzerDatabaseModel.FK__PersonsTo__Perso__182C9B23", "Persons").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Person> PersonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("BuzzerDatabaseModel.FK__PersonsTo__Perso__182C9B23", "Persons");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Person>("BuzzerDatabaseModel.FK__PersonsTo__Perso__182C9B23", "Persons", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BuzzerDatabaseModel", Name="PhoneNumber")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PhoneNumber : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PhoneNumber object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="personID">Initial value of the PersonID property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        public static PhoneNumber CreatePhoneNumber(global::System.Int32 id, global::System.Int32 personID, global::System.String number)
        {
            PhoneNumber phoneNumber = new PhoneNumber();
            phoneNumber.ID = id;
            phoneNumber.PersonID = personID;
            phoneNumber.Number = number;
            return phoneNumber;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PersonID
        {
            get
            {
                return _PersonID;
            }
            set
            {
                OnPersonIDChanging(value);
                ReportPropertyChanging("PersonID");
                _PersonID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PersonID");
                OnPersonIDChanged();
            }
        }
        private global::System.Int32 _PersonID;
        partial void OnPersonIDChanging(global::System.Int32 value);
        partial void OnPersonIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private global::System.String _Number;
        partial void OnNumberChanging(global::System.String value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsValid
        {
            get
            {
                return _IsValid;
            }
            set
            {
                OnIsValidChanging(value);
                ReportPropertyChanging("IsValid");
                _IsValid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsValid");
                OnIsValidChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsValid;
        partial void OnIsValidChanging(Nullable<global::System.Boolean> value);
        partial void OnIsValidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BuzzerDatabaseModel", "FK__PhoneNumb__Perso__0BC6C43E", "Persons")]
        public Person Person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("BuzzerDatabaseModel.FK__PhoneNumb__Perso__0BC6C43E", "Persons").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("BuzzerDatabaseModel.FK__PhoneNumb__Perso__0BC6C43E", "Persons").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Person> PersonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("BuzzerDatabaseModel.FK__PhoneNumb__Perso__0BC6C43E", "Persons");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Person>("BuzzerDatabaseModel.FK__PhoneNumb__Perso__0BC6C43E", "Persons", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
